"use client";
import { FormEvent, useCallback, useMemo, useState } from "react";
import { FiChevronLeft, FiChevronRight, FiEdit2, FiPlus, FiX } from "react-icons/fi";
import { useForecast } from "@/hooks/useForecast";
import { buildMonthlyProjection, ForecastEntry, monthKey, scheduleOccurrences, toDateKey } from "@/lib/forecast";
import { addForecastOneOff, saveForecastOverride, saveOpeningBalance } from "@/lib/forecastStore";
import { UI_TEXT } from "@/lib/uiText";
const money=new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"});
const safetyBuffer=1500;
const forecastStart = new Date(2026, 8, 1);
const forecastStartKey = "2026-09";
const weekday = new Intl.DateTimeFormat("en-AU", { weekday: "long" });
const shortMonth = new Intl.DateTimeFormat("en-AU", { month: "short" });
function ordinal(day: number) { const remainder = day % 100; if (remainder >= 11 && remainder <= 13) return `${day}th`; return `${day}${day % 10 === 1 ? "st" : day % 10 === 2 ? "nd" : day % 10 === 3 ? "rd" : "th"}`; }
function rowTone(state: "past"|"today"|"future", balance: number) {
  if (balance < 0 && state === "today") return "border-red-500 bg-red-200 text-red-950 font-bold dark:bg-red-900 dark:text-red-50";
  if (balance < 0 && state === "future") return "border-red-200 bg-red-50 text-red-900 dark:border-red-900 dark:bg-red-950 dark:text-red-100";
  if (state === "past") return "text-slate-400";
  const emphasis = state === "today" ? "font-bold" : "opacity-75";
  if (balance < 30) return `border-red-500 bg-red-400 text-red-950 dark:bg-red-800 dark:text-red-50 ${emphasis}`;
  if (balance < 50) return `border-red-400 bg-red-300 text-red-950 dark:bg-red-900/80 dark:text-red-50 ${emphasis}`;
  if (balance < 80) return `border-red-300 bg-red-200 text-red-950 dark:bg-red-950/75 dark:text-red-100 ${emphasis}`;
  if (balance < 100) return `border-red-200 bg-red-50 text-red-900 dark:border-red-900 dark:bg-red-950/50 dark:text-red-100 ${emphasis}`;
  if (state === "today") return "border-emerald-500 bg-emerald-50 font-bold";
  return "opacity-65";
}
function recurringBorder(entries: ForecastEntry[]) { const recurring = entries.filter((entry) => entry.source === "recurring" && !entry.excluded); const income = recurring.some((entry) => entry.direction === "income"), expense = recurring.some((entry) => entry.direction === "expense"); if (income && expense) return "border-2 border-amber-400"; if (income) return "border-2 border-emerald-500"; if (expense) return "border-2 border-rose-500"; return ""; }
function recurringText(entries: ForecastEntry[], state: "past"|"today"|"future") { if (state !== "today") return ""; const recurring = entries.filter((entry) => entry.source === "recurring" && !entry.excluded), income = recurring.some((entry) => entry.direction === "income"), expense = recurring.some((entry) => entry.direction === "expense"); if (income && expense) return "text-yellow-500! dark:text-yellow-300!"; if (income) return "text-emerald-600! dark:text-emerald-300!"; if (expense) return "text-rose-600! dark:text-rose-300!"; return ""; }
function todayGlow(state: "past"|"today"|"future") { return state === "today" ? "border-2 border-violet-500! shadow-[0_0_12px_rgba(139,92,246,0.7)] dark:border-violet-400!" : ""; }
function activityText(state: "past"|"today"|"future", entry?: ForecastEntry) { if (entry?.direction === "expense") return entry.source === "recurring" && state === "future" ? "text-sm font-normal text-rose-600 dark:text-rose-400" : "text-sm font-normal text-slate-900 dark:text-slate-100"; return state === "today" ? "text-sm font-normal opacity-80" : "text-sm font-normal text-slate-500 dark:text-slate-400"; }

export default function Forecast(){
 const now=new Date(), data=useForecast();
 const currentMonth = new Date(now.getFullYear(),now.getMonth(),1);
 const forecastEnd = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 12, 1);
 const [anchor,setAnchor]=useState(currentMonth < forecastStart ? forecastStart : currentMonth);
 const [dialog,setDialog]=useState<"opening"|"add"|string|null>(null); const [saving,setSaving]=useState(false);
 const year=anchor.getFullYear(), month=anchor.getMonth(), key=monthKey(year,month), today=toDateKey(now.getFullYear(),now.getMonth(),now.getDate());
 const makeEntries=useCallback((y:number,m:number)=>{const k=monthKey(y,m),list:ForecastEntry[]=data.schedules.flatMap(s=>scheduleOccurrences(s,y,m));data.oneOffs.filter(x=>x.dateKey.startsWith(k)).forEach(x=>list.push({id:x.id,dateKey:x.dateKey,description:x.description,amount:x.amount,direction:x.kind,source:"one-off"}));const totals=new Map<string,number>();data.expenses.forEach(x=>{const d=new Date(x.createdAtMs),dateKey=toDateKey(d.getFullYear(),d.getMonth(),d.getDate());if(dateKey.startsWith(k))totals.set(dateKey,Math.round(((totals.get(dateKey)||0)+x.amount)*100)/100)});totals.forEach((amount,dateKey)=>{const o=data.overrides.find(x=>x.dateKey===dateKey);list.push({id:`expense-${dateKey}`,dateKey,description:UI_TEXT.forecast.expensesTotal,amount:o?.amount??amount,direction:"expense",source:"actual",excluded:o?.excluded})});return list},[data.expenses,data.oneOffs,data.overrides,data.schedules]);
 const entries=useMemo(()=>makeEntries(year,month),[makeEntries,month,year]);
 const carry=useMemo(()=>{if(key===forecastStartKey)return 0;const p=new Date(year,month-1,1),pk=monthKey(p.getFullYear(),p.getMonth()),po=data.months.find(x=>x.id===pk)?.openingBalance??0;return buildMonthlyProjection({year:p.getFullYear(),monthIndex:p.getMonth(),openingBalance:po,entries:makeEntries(p.getFullYear(),p.getMonth()),todayKey:today}).closingBalance},[data.months,key,makeEntries,month,today,year]), opening=data.months.find(x=>x.id===key)?.openingBalance??carry;
 const projection=useMemo(()=>buildMonthlyProjection({year,monthIndex:month,openingBalance:opening,entries,todayKey:today}),[entries,month,opening,today,year]);
 async function save(action:()=>Promise<void>){setSaving(true);try{await action();setDialog(null)}finally{setSaving(false)}}
 function submitOpening(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),old=data.months.find(x=>x.id===key)?.openingBalance??null;void save(()=>saveOpeningBalance(key,old,Number(f.get("amount")),String(f.get("reason"))))}
 function submitAdd(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>addForecastOneOff({kind:f.get("kind")==="income"?"income":"expense",description:String(f.get("description")),amount:Number(f.get("amount")),dateKey:String(f.get("date")),reason:String(f.get("reason"))}))}
 function submitDay(e:FormEvent<HTMLFormElement>,dateKey:string,entry:ForecastEntry){e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>saveForecastOverride(dateKey,entry.amount,Number(f.get("amount")),!!entry.excluded,f.get("included")!=="on",String(f.get("reason"))))}
 return <main className="mx-auto w-full max-w-md p-4 pb-28">{data.error&&<p className="mb-4 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{data.error}</p>}
 <div className={`mb-3 rounded-lg p-3 text-sm ${projection.lowestDay.closingBalance<safetyBuffer?"bg-amber-50 text-amber-900":"bg-emerald-50 text-emerald-900"}`}><b>{UI_TEXT.forecast.lowestBalance}: {money.format(projection.lowestDay.closingBalance)}</b><p className="text-xs">{projection.lowestDay.closingBalance<safetyBuffer?UI_TEXT.forecast.bufferGap(money.format(safetyBuffer-projection.lowestDay.closingBalance)):UI_TEXT.forecast.bufferSafe}</p></div>
 <section className="mb-3 rounded-xl border bg-white p-2 dark:bg-slate-900"><div className="flex justify-between"><button disabled={key===forecastStartKey} onClick={()=>setAnchor(new Date(year,month-1,1))} className="disabled:cursor-not-allowed disabled:opacity-25" aria-label={UI_TEXT.forecast.previousMonth}><FiChevronLeft/></button><b>{new Intl.DateTimeFormat("en-AU",{month:"long",year:"numeric"}).format(anchor)}</b><button disabled={anchor>=forecastEnd} onClick={()=>setAnchor(new Date(year,month+1,1))} className="disabled:cursor-not-allowed disabled:opacity-25" aria-label={UI_TEXT.forecast.nextMonth}><FiChevronRight/></button></div><div className="mt-2 grid grid-cols-2 gap-1"><Card label={UI_TEXT.forecast.carriedForward} value={money.format(carry)}/><Card label={UI_TEXT.forecast.openingBalance} value={money.format(opening)} action={<button onClick={()=>setDialog("opening")} aria-label={UI_TEXT.forecast.editOpeningBalance}><FiEdit2 size={13}/></button>}/></div></section>
 <section className="rounded-xl border bg-white p-2 dark:bg-slate-900"><ol className="space-y-2">{projection.days.map(d=>{const date=new Date(year,month,d.day),rows=Math.max(2,d.entries.length);return <li key={d.dateKey} className={`rounded-lg border p-2 ${rowTone(d.state,d.closingBalance)} ${recurringBorder(d.entries)} ${todayGlow(d.state)} ${recurringText(d.entries,d.state)}`}><div className="grid grid-cols-[5.5rem_minmax(0,1fr)_auto] items-baseline gap-x-2 gap-y-0.5 text-sm">{Array.from({length:rows},(_,index)=>{const entry=d.entries[index];return <div key={`${d.dateKey}-${index}`} className="contents"><time dateTime={index===0?d.dateKey:undefined} className="text-xs"><span className={index===0?"font-semibold":""}>{index===0?weekday.format(date):index===1?<>{ordinal(d.day)} {shortMonth.format(date)}{d.state==="today"&&<span className="ml-1 font-bold uppercase">{UI_TEXT.forecast.today}</span>}</>:null}</span></time><span className={`min-w-0 truncate ${activityText(d.state,entry)} ${entry?.excluded?"line-through opacity-50":""}`}>{entry?.description??(index===0&&!d.entries.length?UI_TEXT.forecast.noActivity:"")}</span><span className={`flex items-center justify-end gap-1 whitespace-nowrap text-right ${activityText(d.state,entry)} ${entry?.excluded?"line-through opacity-50":""}`}>{entry?`${entry.direction==="income"?"+":"−"}${money.format(entry.amount)}`:""}{entry?.source==="actual"&&<button onClick={()=>setDialog(d.dateKey)} aria-label={UI_TEXT.forecast.editDay(d.dateKey)}><FiEdit2/></button>}</span></div>})}<span className="col-span-2"/><span className="whitespace-nowrap text-right"><b>{money.format(d.closingBalance)}</b></span></div></li>})}</ol></section>
 <section className="mt-3 grid grid-cols-2 gap-1 rounded-xl border bg-white p-2 dark:bg-slate-900"><Card label={UI_TEXT.forecast.difference} value={money.format(opening-carry)}/><Card label={UI_TEXT.forecast.projectedClosing} value={money.format(projection.closingBalance)}/></section>
 <button onClick={()=>setDialog("add")} aria-label={UI_TEXT.forecast.add} className="fixed bottom-24 left-1/2 z-30 flex size-14 translate-x-[calc(12rem-3.5rem)] items-center justify-center rounded-full bg-emerald-600 text-white"><FiPlus/></button>
 {dialog==="opening"&&<Modal title={UI_TEXT.forecast.editOpeningBalance} close={()=>setDialog(null)}><form onSubmit={submitOpening}><Input name="amount" label={UI_TEXT.forecast.openingBalance} type="number" value={opening}/><Reason/><Actions saving={saving}/></form></Modal>}
 {dialog==="add"&&<Modal title={UI_TEXT.forecast.addOneOffTitle} close={()=>setDialog(null)}><form onSubmit={submitAdd}><label>Type<select name="kind" className="input w-full"><option value="expense">{UI_TEXT.forecast.unexpectedExpense}</option><option value="income">{UI_TEXT.forecast.oneOffIncome}</option></select></label><Input name="date" label="Date" type="date" value={`${key}-01`}/><Input name="description" label="Description"/><Input name="amount" label="Amount" type="number"/><Reason/><Actions saving={saving}/></form></Modal>}
 {dialog?.match(/^\d{4}-/)&&(()=>{const day=projection.days.find(d=>d.dateKey===dialog),entry=day?.entries.find(x=>x.source==="actual");return entry?<Modal title={UI_TEXT.forecast.editDay(dialog)} close={()=>setDialog(null)}><form onSubmit={e=>submitDay(e,dialog,entry)}><Input name="amount" label={UI_TEXT.forecast.forecastAmount} type="number" value={entry.amount}/><label className="flex justify-between">{UI_TEXT.forecast.included}<input name="included" type="checkbox" defaultChecked={!entry.excluded}/></label><Reason/><Actions saving={saving}/></form></Modal>:null})()}
 </main>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="dialog" aria-label={title} className="w-full max-w-sm rounded-xl bg-white p-4 dark:bg-slate-900"><div className="flex justify-between"><h2 className="font-bold">{title}</h2><button onClick={close} aria-label="Close"><FiX/></button></div>{children}</section></div>}
function Input({name,label,type="text",value}:{name:string;label:string;type?:string;value?:string|number}){return <label className="mt-3 block">{label}<input required name={name} type={type} defaultValue={value} step={type==="number"?"0.01":undefined} className="input w-full px-3 py-2"/></label>};function Reason(){return <label className="mt-3 block">{UI_TEXT.forecast.changeReason}<textarea required name="reason" maxLength={160} className="input w-full"/></label>};function Actions({saving}:{saving:boolean}){return <button disabled={saving} className="mt-4 w-full rounded-lg bg-emerald-600 p-2 text-white">{saving?UI_TEXT.common.pleaseWait:UI_TEXT.common.save}</button>};function Card({label,value,action}:{label:string;value:string;action?:React.ReactNode}){return <div className="flex min-w-0 items-center justify-between gap-1 rounded-md bg-slate-50 px-2 py-1.5 text-xs dark:bg-slate-800"><small className="truncate text-xs leading-tight">{label}</small><div className="flex shrink-0 items-center gap-1 whitespace-nowrap font-bold leading-tight">{value}{action}</div></div>}
