"use client";
import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { FiArrowUp, FiCheck, FiChevronLeft, FiChevronRight, FiEdit2, FiPlus, FiTrash2, FiX } from "react-icons/fi";
import { useForecast } from "@/hooks/useForecast";
import { buildMonthlyProjection, calculateForecastExpenseTotal, ForecastEntry, monthKey, scheduleOccurrences, toDateKey } from "@/lib/forecast";
import { addForecastOneOff, excludeRecurringOccurrence, saveForecastOverride, saveOpeningBalance } from "@/lib/forecastStore";
import { UI_TEXT } from "@/lib/uiText";
import type { Expense, ForecastOverride } from "@/lib/types";
import { FORECAST_SAFETY_BUFFER } from "@/lib/config";
const money=new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"});
const forecastStart = new Date(2026, 8, 1);
const forecastStartKey = "2026-09";
const weekday = new Intl.DateTimeFormat("en-AU", { weekday: "long" });
const shortMonth = new Intl.DateTimeFormat("en-AU", { month: "short" });
function ordinal(day: number) { const remainder = day % 100; if (remainder >= 11 && remainder <= 13) return `${day}th`; return `${day}${day % 10 === 1 ? "st" : day % 10 === 2 ? "nd" : day % 10 === 3 ? "rd" : "th"}`; }
function signedMoney(value: number) { return value > 0 ? `+${money.format(value)}` : money.format(value); }
function expenseDateKey(expense: Expense) { const date = new Date(expense.createdAtMs); return toDateKey(date.getFullYear(), date.getMonth(), date.getDate()); }
function rowTone(state: "past"|"today"|"future", balance: number) {
  if (balance < 0 && state === "today") return "border-red-500 bg-red-200 text-red-950 font-bold dark:bg-red-900 dark:text-red-50";
  if (balance < 0 && state === "future") return "border-red-200 bg-red-50 text-red-900 dark:border-red-900 dark:bg-red-950 dark:text-red-100";
  if (state === "past") return "text-slate-400";
  const emphasis = state === "today" ? "font-bold" : "opacity-75";
  if (balance < 30) return `border-red-500 bg-red-400 text-red-950 dark:bg-red-800 dark:text-red-50 ${emphasis}`;
  if (balance < 50) return `border-red-400 bg-red-300 text-red-950 dark:bg-red-900/80 dark:text-red-50 ${emphasis}`;
  if (balance < 80) return `border-red-300 bg-red-200 text-red-950 dark:bg-red-950/75 dark:text-red-100 ${emphasis}`;
  if (balance < 100) return `border-red-200 bg-red-50 text-red-900 dark:border-red-900 dark:bg-red-950/50 dark:text-red-100 ${emphasis}`;
  if (state === "today") return "border-emerald-500 bg-emerald-50 font-bold";
  return "opacity-65";
}
function recurringBorder(entries: ForecastEntry[]) { const recurring = entries.filter((entry) => entry.source === "recurring" && !entry.excluded); const income = recurring.some((entry) => entry.direction === "income"), expense = recurring.some((entry) => entry.direction === "expense"); if (income && expense) return "border-2 border-amber-400"; if (income) return "border-2 border-emerald-500"; if (expense) return "border-2 border-rose-500"; return ""; }
function recurringText(entries: ForecastEntry[], state: "past"|"today"|"future") { if (state !== "today") return ""; const recurring = entries.filter((entry) => entry.source === "recurring" && !entry.excluded), income = recurring.some((entry) => entry.direction === "income"), expense = recurring.some((entry) => entry.direction === "expense"); if (income && expense) return "text-yellow-500! dark:text-yellow-300!"; if (income) return "text-emerald-600! dark:text-emerald-300!"; if (expense) return "text-rose-600! dark:text-rose-300!"; return ""; }
function todayGlow(state: "past"|"today"|"future") { return state === "today" ? "border-2 border-violet-500! shadow-[0_0_12px_rgba(139,92,246,0.7)] dark:border-violet-400!" : ""; }
function activityText(state: "past"|"today"|"future", entry?: ForecastEntry) { if (entry?.direction === "expense") return entry.source === "recurring" && state === "future" ? "text-sm font-normal text-rose-600 dark:text-rose-400" : "text-sm font-normal text-slate-900 dark:text-slate-100"; return state === "today" ? "text-sm font-normal opacity-80" : "text-sm font-normal text-slate-500 dark:text-slate-400"; }

export default function Forecast(){
 const now=new Date(), data=useForecast();
 const currentMonth = new Date(now.getFullYear(),now.getMonth(),1);
 const forecastEnd = new Date(currentMonth.getFullYear(), currentMonth.getMonth() + 12, 1);
 const [anchor,setAnchor]=useState(currentMonth < forecastStart ? forecastStart : currentMonth);
 const [todayJump,setTodayJump]=useState(0); const timelineRef=useRef<HTMLElement>(null),todayRowRef=useRef<HTMLLIElement>(null);
 const [dialog,setDialog]=useState<"opening"|"add"|string|null>(null); const [occurrenceToExclude,setOccurrenceToExclude]=useState<ForecastEntry|null>(null); const [saving,setSaving]=useState(false),[saveError,setSaveError]=useState("");
 const year=anchor.getFullYear(), month=anchor.getMonth(), key=monthKey(year,month), today=toDateKey(now.getFullYear(),now.getMonth(),now.getDate());
 const makeEntries=useCallback((y:number,m:number)=>{const k=monthKey(y,m),excludedOccurrences=new Set(data.occurrenceOverrides.map(item=>item.occurrenceId)),list:ForecastEntry[]=data.schedules.flatMap(s=>scheduleOccurrences(s,y,m)).filter(entry=>!excludedOccurrences.has(entry.id));data.oneOffs.filter(x=>x.dateKey.startsWith(k)).forEach(x=>list.push({id:x.id,dateKey:x.dateKey,description:x.description,amount:x.amount,direction:x.kind,source:"one-off"}));const expensesByDate=new Map<string,Expense[]>();data.expenses.forEach(expense=>{const dateKey=expenseDateKey(expense);if(dateKey.startsWith(k))expensesByDate.set(dateKey,[...(expensesByDate.get(dateKey)||[]),expense])});expensesByDate.forEach((expenses,dateKey)=>{const override=data.overrides.find(item=>item.dateKey===dateKey),total=calculateForecastExpenseTotal(expenses,override);list.push({id:`expense-${dateKey}`,dateKey,description:UI_TEXT.forecast.expensesTotal,amount:total.finalTotal,direction:"expense",source:"actual",excluded:override?.excluded})});return list},[data.expenses,data.occurrenceOverrides,data.oneOffs,data.overrides,data.schedules]);
 const entries=useMemo(()=>makeEntries(year,month),[makeEntries,month,year]);
 const carry=useMemo(()=>{if(key===forecastStartKey)return 0;const p=new Date(year,month-1,1),pk=monthKey(p.getFullYear(),p.getMonth()),po=data.months.find(x=>x.id===pk)?.openingBalance??0;return buildMonthlyProjection({year:p.getFullYear(),monthIndex:p.getMonth(),openingBalance:po,entries:makeEntries(p.getFullYear(),p.getMonth()),todayKey:today}).closingBalance},[data.months,key,makeEntries,month,today,year]), opening=data.months.find(x=>x.id===key)?.openingBalance??carry;
 const projection=useMemo(()=>buildMonthlyProjection({year,monthIndex:month,openingBalance:opening,entries,todayKey:today}),[entries,month,opening,today,year]);
 const lowestDateLabel=`${ordinal(projection.lowestDay.day)} ${shortMonth.format(new Date(year,month,projection.lowestDay.day))}`;
 useEffect(()=>{if(!todayJump)return;const frame=window.requestAnimationFrame(()=>{const timeline=timelineRef.current,row=todayRowRef.current;if(!timeline||!row)return;const top=row.getBoundingClientRect().top-timeline.getBoundingClientRect().top+timeline.scrollTop-(timeline.clientHeight-row.clientHeight)/2;timeline.scrollTo({top:Math.max(0,top),behavior:"smooth"})});return()=>window.cancelAnimationFrame(frame)},[key,todayJump]);
 async function save(action:()=>Promise<void>){setSaving(true);setSaveError("");try{await action();setDialog(null)}catch(error){console.error("Saving Forecast change failed",error);setSaveError(UI_TEXT.forecast.saveAdjustmentFailed)}finally{setSaving(false)}}
 function submitOpening(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),old=data.months.find(x=>x.id===key)?.openingBalance??null;void save(()=>saveOpeningBalance(key,old,Number(f.get("amount")),String(f.get("reason"))))}
 function submitAdd(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>addForecastOneOff({kind:f.get("kind")==="income"?"income":"expense",description:String(f.get("description")),amount:Number(f.get("amount")),dateKey:String(f.get("date")),reason:String(f.get("reason"))}))}
 return <main className="mx-auto w-full max-w-md p-4 pb-28">{(data.error||saveError)&&<p role="alert" className="fixed inset-x-4 top-20 z-[60] mx-auto max-w-sm rounded-lg bg-rose-100 p-3 text-sm font-semibold text-rose-800 shadow-lg dark:bg-rose-950 dark:text-rose-200">{saveError||data.error}</p>}
 <section className="mb-3 rounded-xl border bg-white p-2 dark:bg-slate-900"><div className="flex justify-between"><button disabled={key===forecastStartKey} onClick={()=>setAnchor(new Date(year,month-1,1))} className="disabled:cursor-not-allowed disabled:opacity-25" aria-label={UI_TEXT.forecast.previousMonth}><FiChevronLeft/></button><b>{new Intl.DateTimeFormat("en-AU",{month:"long",year:"numeric"}).format(anchor)}</b><button disabled={anchor>=forecastEnd} onClick={()=>setAnchor(new Date(year,month+1,1))} className="disabled:cursor-not-allowed disabled:opacity-25" aria-label={UI_TEXT.forecast.nextMonth}><FiChevronRight/></button></div><div className="mt-2 grid grid-cols-2 gap-1"><Card label={UI_TEXT.forecast.carriedForward} value={money.format(carry)}/><Card label={UI_TEXT.forecast.openingBalance} value={money.format(opening)} action={<button onClick={()=>setDialog("opening")} aria-label={UI_TEXT.forecast.editOpeningBalance}><FiEdit2 size={13}/></button>}/></div><div className={`mt-2 rounded-md px-2 py-1.5 text-xs ${projection.lowestDay.closingBalance<FORECAST_SAFETY_BUFFER?"bg-amber-50 text-amber-900":"bg-emerald-50 text-emerald-900"}`}><b className={projection.lowestDay.closingBalance<0?"text-rose-700 dark:text-rose-400":undefined}>{UI_TEXT.forecast.lowestBalanceOn(money.format(projection.lowestDay.closingBalance),lowestDateLabel)}</b><p className="flex items-center gap-1">{projection.lowestDay.closingBalance<FORECAST_SAFETY_BUFFER&&<FiArrowUp aria-hidden="true" className="shrink-0"/>}{projection.lowestDay.closingBalance<0?UI_TEXT.forecast.balanceTargets(money.format(Math.abs(projection.lowestDay.closingBalance)),money.format(FORECAST_SAFETY_BUFFER-projection.lowestDay.closingBalance),money.format(FORECAST_SAFETY_BUFFER)):projection.lowestDay.closingBalance<FORECAST_SAFETY_BUFFER?UI_TEXT.forecast.bufferNeeded(money.format(FORECAST_SAFETY_BUFFER-projection.lowestDay.closingBalance),money.format(FORECAST_SAFETY_BUFFER)):UI_TEXT.forecast.bufferSafe(money.format(FORECAST_SAFETY_BUFFER))}</p></div></section>
 <div className="mb-2 flex items-center justify-between px-1"><h2 className="font-bold">{UI_TEXT.forecast.timelineTitle}</h2><div className="flex items-center gap-2"><button onClick={()=>{setAnchor(currentMonth < forecastStart ? forecastStart : currentMonth);setTodayJump(value=>value+1)}} className="h-9 rounded-lg border border-violet-300 px-3 text-sm font-semibold text-violet-700 hover:bg-violet-50 dark:border-violet-700 dark:text-violet-300 dark:hover:bg-violet-950">{UI_TEXT.forecast.today}</button><button onClick={()=>setDialog("add")} aria-label={UI_TEXT.forecast.add} className="flex size-9 items-center justify-center rounded-lg bg-emerald-600 text-white shadow-sm hover:bg-emerald-700"><FiPlus/></button></div></div>
 <section ref={timelineRef} className="max-h-[calc(100dvh-25rem)] overflow-y-auto overscroll-contain rounded-xl border bg-white p-2 dark:bg-slate-900"><ol className="space-y-2">{projection.days.map(d=>{const date=new Date(year,month,d.day),rows=Math.max(2,d.entries.length);return <li ref={d.state==="today"?todayRowRef:undefined} key={d.dateKey} className={`rounded-lg border p-2 ${rowTone(d.state,d.closingBalance)} ${recurringBorder(d.entries)} ${todayGlow(d.state)} ${recurringText(d.entries,d.state)}`}><div className="grid grid-cols-[5.5rem_minmax(0,1fr)_auto] items-baseline gap-x-2 gap-y-0.5 text-sm">{Array.from({length:rows},(_,index)=>{const entry=d.entries[index];return <div key={`${d.dateKey}-${index}`} className="contents"><time dateTime={index===0?d.dateKey:undefined} className="text-xs"><span className={index===0?"font-semibold":""}>{index===0?weekday.format(date):index===1?<>{ordinal(d.day)} {shortMonth.format(date)}{d.state==="today"&&<span className="ml-1 font-bold uppercase">{UI_TEXT.forecast.today}</span>}</>:null}</span></time><span className={`flex min-w-0 items-center gap-1 ${activityText(d.state,entry)} ${entry?.excluded?"line-through opacity-50":""}`}><span className="truncate">{entry?.description??(index===0&&!d.entries.length?UI_TEXT.forecast.noActivity:"")}</span>{entry?.source==="recurring"&&entry.direction==="expense"&&d.state!=="future"&&<button type="button" onClick={()=>setOccurrenceToExclude(entry)} aria-label={UI_TEXT.forecast.excludeOccurrence(entry.description,entry.dateKey)} className="shrink-0 text-rose-600"><FiTrash2 size={13}/></button>}</span><span className={`flex items-center justify-end gap-1 whitespace-nowrap text-right ${activityText(d.state,entry)} ${entry?.excluded?"line-through opacity-50":""}`}>{entry?`${entry.direction==="income"?"+":"−"}${money.format(entry.amount)}`:""}{entry?.source==="actual"&&<button onClick={()=>setDialog(d.dateKey)} aria-label={UI_TEXT.forecast.editDay(d.dateKey)}><FiEdit2/></button>}</span></div>})}<span className="col-span-2"/><span className="whitespace-nowrap text-right"><b>{money.format(d.closingBalance)}</b></span></div></li>})}</ol></section>
 <section className="mt-3 grid grid-cols-2 gap-1 rounded-xl border bg-white p-2 dark:bg-slate-900"><Card label={UI_TEXT.forecast.difference} value={signedMoney(opening-carry)}/><Card label={UI_TEXT.forecast.projectedClosing} value={money.format(projection.closingBalance)}/></section>
 {dialog==="opening"&&<Modal title={UI_TEXT.forecast.editOpeningBalance} close={()=>setDialog(null)}><form onSubmit={submitOpening}><Input name="amount" label={UI_TEXT.forecast.openingBalance} type="number" value={opening}/><Reason/><Actions saving={saving}/></form></Modal>}
 {dialog==="add"&&<Modal title={UI_TEXT.forecast.addOneOffTitle} close={()=>setDialog(null)}><form onSubmit={submitAdd}><label>Type<select name="kind" className="input w-full"><option value="expense">{UI_TEXT.forecast.unexpectedExpense}</option><option value="income">{UI_TEXT.forecast.oneOffIncome}</option></select></label><Input name="date" label="Date" type="date" value={`${key}-01`}/><Input name="description" label="Description"/><Input name="amount" label="Amount" type="number"/><Reason/><Actions saving={saving}/></form></Modal>}
 {dialog?.match(/^\d{4}-/)&&<DailyExpenseEditor dateKey={dialog} expenses={data.expenses.filter(expense=>expenseDateKey(expense)===dialog)} override={data.overrides.find(item=>item.dateKey===dialog)} saving={saving} close={()=>setDialog(null)} save={action=>void save(action)}/>}
 {occurrenceToExclude&&<Modal title={UI_TEXT.forecast.excludeOccurrenceTitle} close={()=>setOccurrenceToExclude(null)}><p className="mt-3 text-sm">{UI_TEXT.forecast.excludeOccurrenceHelp(occurrenceToExclude.description,occurrenceToExclude.dateKey)}</p><form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget),entry=occurrenceToExclude,scheduleId=entry.scheduleId;if(!scheduleId)return;void save(async()=>{await excludeRecurringOccurrence({occurrenceId:entry.id,scheduleId,dateKey:entry.dateKey,name:entry.description,amount:entry.amount,reason:String(form.get("reason"))});setOccurrenceToExclude(null)})}}><Reason/><button disabled={saving} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-rose-600 p-2 text-white"><FiTrash2/>{saving?UI_TEXT.common.pleaseWait:UI_TEXT.forecast.excludeThisOccurrence}</button></form></Modal>}
 </main>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="dialog" aria-label={title} className="w-full max-w-sm rounded-xl bg-white p-4 dark:bg-slate-900"><div className="flex justify-between"><h2 className="font-bold">{title}</h2><button onClick={close} aria-label="Close"><FiX/></button></div>{children}</section></div>}
function DailyExpenseEditor({dateKey,expenses,override,saving,close,save}:{dateKey:string;expenses:Expense[];override?:ForecastOverride;saving:boolean;close:()=>void;save:(action:()=>Promise<void>)=>void}){
 const legacy=!!override&&!override.excludedExpenseIds, initialExcluded=override?.excludedExpenseIds??[];
 const [excludedIds,setExcludedIds]=useState(initialExcluded),[manual,setManual]=useState(!!override?.locked||legacy),[manualAmount,setManualAmount]=useState(String(override?.amount??0));
 const selected=expenses.filter(expense=>!excludedIds.includes(expense.id)),sourceTotal=Math.round(expenses.reduce((sum,expense)=>sum+expense.amount,0)*100)/100,selectedTotal=Math.round(selected.reduce((sum,expense)=>sum+expense.amount,0)*100)/100;
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget),amount=manual?Number(manualAmount):selectedTotal;save(()=>saveForecastOverride({dateKey,oldAmount:calculateForecastExpenseTotal(expenses,override).finalTotal,amount,oldExcludedExpenseIds:initialExcluded,excludedExpenseIds:excludedIds,oldLocked:!!override?.locked||legacy,locked:manual,reason:String(form.get("reason"))}))}
 return <Modal title={UI_TEXT.forecast.editDay(dateKey)} close={close}><form onSubmit={submit}><p className="mt-2 text-sm text-slate-500">{UI_TEXT.forecast.editDayHelp}</p><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{expenses.map(expense=>{const included=!excludedIds.includes(expense.id);return <label key={expense.id} className="grid grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" checked={included} aria-label={UI_TEXT.forecast.includeExpense(expense.description)} onChange={()=>setExcludedIds(current=>included?current.concat(expense.id):current.filter(id=>id!==expense.id))}/><span className="min-w-0"><b className="block truncate">{expense.description}</b><small className="text-slate-500">{expense.createdBy} · {expense.category}</small></span><span className={included?"font-semibold":"text-slate-400 line-through"}>{money.format(expense.amount)}</span></label>})}</div><div className="mt-3 rounded-lg bg-slate-50 p-2 text-sm dark:bg-slate-800"><div className="flex justify-between"><span>{UI_TEXT.forecast.sourceExpenseTotal}</span><b>{money.format(sourceTotal)}</b></div><div className="flex justify-between text-slate-500"><span>{UI_TEXT.forecast.excludedExpenseTotal}</span><span>−{money.format(sourceTotal-selectedTotal)}</span></div><div className="mt-1 flex items-center justify-between border-t pt-1"><span>{UI_TEXT.forecast.forecastExpenseTotal}</span>{manual?<input required type="number" step="0.01" value={manualAmount} onChange={event=>setManualAmount(event.target.value)} className="input w-28 px-2 py-1 text-right font-bold"/>:<b>{money.format(selectedTotal)}</b>}</div><p className="mt-1 text-xs text-slate-500">{manual?UI_TEXT.forecast.lockedExpenseTotal:UI_TEXT.forecast.automaticExpenseTotal}</p></div><button type="button" onClick={()=>{setManual(value=>!value);if(!manual)setManualAmount(String(selectedTotal))}} className="mt-3 flex items-center gap-2 text-sm font-semibold text-violet-700"><FiEdit2/>{manual?UI_TEXT.forecast.useSelectedTransactions:UI_TEXT.forecast.editManualTotal}</button><Reason/><button disabled={saving} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-600 p-2 text-white"><FiCheck/>{saving?UI_TEXT.common.pleaseWait:UI_TEXT.forecast.saveAdjustments}</button></form></Modal>
}
function Input({name,label,type="text",value}:{name:string;label:string;type?:string;value?:string|number}){return <label className="mt-3 block">{label}<input required name={name} type={type} defaultValue={value} step={type==="number"?"0.01":undefined} className="input w-full px-3 py-2"/></label>};function Reason(){return <label className="mt-3 block">{UI_TEXT.forecast.changeReason}<textarea required name="reason" maxLength={160} className="input w-full"/></label>};function Actions({saving}:{saving:boolean}){return <button disabled={saving} className="mt-4 w-full rounded-lg bg-emerald-600 p-2 text-white">{saving?UI_TEXT.common.pleaseWait:UI_TEXT.common.save}</button>};function Card({label,value,action}:{label:string;value:string;action?:React.ReactNode}){return <div className="flex min-w-0 items-center justify-between gap-1 rounded-md bg-slate-50 px-2 py-1.5 text-xs dark:bg-slate-800"><small className="truncate text-xs leading-tight">{label}</small><div className="flex shrink-0 items-center gap-1 whitespace-nowrap font-bold leading-tight">{value}{action}</div></div>}
