"use client";
import { FormEvent, useCallback, useMemo, useState } from "react";
import { FiChevronLeft, FiChevronRight, FiEdit2, FiPlus, FiTrendingUp, FiX } from "react-icons/fi";
import { useForecast } from "@/hooks/useForecast";
import { buildMonthlyProjection, ForecastEntry, monthKey, scheduleOccurrences, toDateKey } from "@/lib/forecast";
import { addForecastOneOff, saveForecastOverride, saveOpeningBalance } from "@/lib/forecastStore";
import { UI_TEXT } from "@/lib/uiText";
const money=new Intl.NumberFormat("en-AU",{style:"currency",currency:"AUD"});
const safetyBuffer=1500;
const weekday = new Intl.DateTimeFormat("en-AU", { weekday: "long" });
const shortMonth = new Intl.DateTimeFormat("en-AU", { month: "short" });
function ordinal(day: number) { const remainder = day % 100; if (remainder >= 11 && remainder <= 13) return `${day}th`; return `${day}${day % 10 === 1 ? "st" : day % 10 === 2 ? "nd" : day % 10 === 3 ? "rd" : "th"}`; }
function rowTone(state: "past"|"today"|"future", balance: number) { if (balance < 0 && state === "today") return "border-red-500 bg-red-200 text-red-950 font-bold dark:bg-red-900 dark:text-red-50"; if (balance < 0 && state === "future") return "border-red-200 bg-red-50 text-red-900 dark:border-red-900 dark:bg-red-950 dark:text-red-100"; if (state === "today") return "border-emerald-500 bg-emerald-50 font-bold"; if (state === "past") return "text-slate-400"; return "opacity-65"; }
function recurringBorder(entries: ForecastEntry[]) { const recurring = entries.filter((entry) => entry.source === "recurring" && !entry.excluded); const income = recurring.some((entry) => entry.direction === "income"), expense = recurring.some((entry) => entry.direction === "expense"); if (income && expense) return "border-2 border-amber-400"; if (income) return "border-2 border-emerald-500"; if (expense) return "border-2 border-rose-500"; return ""; }

export default function Forecast(){
 const now=new Date(), data=useForecast();
 const [anchor,setAnchor]=useState(new Date(now.getFullYear(),now.getMonth(),1));
 const [dialog,setDialog]=useState<"opening"|"add"|string|null>(null); const [saving,setSaving]=useState(false);
 const year=anchor.getFullYear(), month=anchor.getMonth(), key=monthKey(year,month), today=toDateKey(now.getFullYear(),now.getMonth(),now.getDate());
 const makeEntries=useCallback((y:number,m:number)=>{const k=monthKey(y,m),list:ForecastEntry[]=data.schedules.flatMap(s=>scheduleOccurrences(s,y,m));data.oneOffs.filter(x=>x.dateKey.startsWith(k)).forEach(x=>list.push({id:x.id,dateKey:x.dateKey,description:x.description,amount:x.amount,direction:x.kind,source:"one-off"}));const totals=new Map<string,number>();data.expenses.forEach(x=>{const d=new Date(x.createdAtMs),dateKey=toDateKey(d.getFullYear(),d.getMonth(),d.getDate());if(dateKey.startsWith(k))totals.set(dateKey,Math.round(((totals.get(dateKey)||0)+x.amount)*100)/100)});totals.forEach((amount,dateKey)=>{const o=data.overrides.find(x=>x.dateKey===dateKey);list.push({id:`expense-${dateKey}`,dateKey,description:UI_TEXT.forecast.expensesTotal,amount:o?.amount??amount,direction:"expense",source:"actual",excluded:o?.excluded})});return list},[data.expenses,data.oneOffs,data.overrides,data.schedules]);
 const entries=useMemo(()=>makeEntries(year,month),[makeEntries,month,year]);
 const carry=useMemo(()=>{const p=new Date(year,month-1,1),pk=monthKey(p.getFullYear(),p.getMonth()),po=data.months.find(x=>x.id===pk)?.openingBalance??0;return buildMonthlyProjection({year:p.getFullYear(),monthIndex:p.getMonth(),openingBalance:po,entries:makeEntries(p.getFullYear(),p.getMonth()),todayKey:today}).closingBalance},[data.months,makeEntries,month,today,year]), opening=data.months.find(x=>x.id===key)?.openingBalance??carry;
 const projection=useMemo(()=>buildMonthlyProjection({year,monthIndex:month,openingBalance:opening,entries,todayKey:today}),[entries,month,opening,today,year]);
 async function save(action:()=>Promise<void>){setSaving(true);try{await action();setDialog(null)}finally{setSaving(false)}}
 function submitOpening(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),old=data.months.find(x=>x.id===key)?.openingBalance??null;void save(()=>saveOpeningBalance(key,old,Number(f.get("amount")),String(f.get("reason"))))}
 function submitAdd(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>addForecastOneOff({kind:f.get("kind")==="income"?"income":"expense",description:String(f.get("description")),amount:Number(f.get("amount")),dateKey:String(f.get("date")),reason:String(f.get("reason"))}))}
 function submitDay(e:FormEvent<HTMLFormElement>,dateKey:string,entry:ForecastEntry){e.preventDefault();const f=new FormData(e.currentTarget);void save(()=>saveForecastOverride(dateKey,entry.amount,Number(f.get("amount")),!!entry.excluded,f.get("included")!=="on",String(f.get("reason"))))}
 return <main className="mx-auto w-full max-w-md p-4 pb-28"><header className="mb-4 rounded-xl bg-emerald-50 p-4"><div className="flex items-center gap-2"><FiTrendingUp/><h1 className="text-xl font-bold">{UI_TEXT.forecast.title}</h1></div><p className="text-sm">{UI_TEXT.forecast.subtitle}</p>{data.error&&<p className="text-sm text-rose-700">{data.error}</p>}</header>
 <section className="mb-4 rounded-xl border bg-white p-4 dark:bg-slate-900"><div className="flex justify-between"><button onClick={()=>setAnchor(new Date(year,month-1,1))} aria-label={UI_TEXT.forecast.previousMonth}><FiChevronLeft/></button><b>{new Intl.DateTimeFormat("en-AU",{month:"long",year:"numeric"}).format(anchor)}</b><button onClick={()=>setAnchor(new Date(year,month+1,1))} aria-label={UI_TEXT.forecast.nextMonth}><FiChevronRight/></button></div><div className="mt-4 grid grid-cols-2 gap-2"><Card label={UI_TEXT.forecast.carriedForward} value={money.format(carry)}/><Card label={UI_TEXT.forecast.openingBalance} value={money.format(opening)} action={<button onClick={()=>setDialog("opening")} aria-label={UI_TEXT.forecast.editOpeningBalance}><FiEdit2/></button>}/><Card label={UI_TEXT.forecast.difference} value={money.format(opening-carry)}/><Card label={UI_TEXT.forecast.projectedClosing} value={money.format(projection.closingBalance)}/></div><div className={`mt-2 rounded-lg p-3 text-sm ${projection.lowestDay.closingBalance<safetyBuffer?"bg-amber-50 text-amber-900":"bg-emerald-50 text-emerald-900"}`}><b>{UI_TEXT.forecast.lowestBalance}: {money.format(projection.lowestDay.closingBalance)}</b><p className="text-xs">{projection.lowestDay.closingBalance<safetyBuffer?UI_TEXT.forecast.bufferGap(money.format(safetyBuffer-projection.lowestDay.closingBalance)):UI_TEXT.forecast.bufferSafe}</p></div></section>
 <section className="rounded-xl border bg-white p-3 dark:bg-slate-900"><h2 className="mb-3 font-bold">{UI_TEXT.forecast.timelineTitle}</h2><ol className="space-y-2">{projection.days.map(d=>{const date=new Date(year,month,d.day);return <li key={d.dateKey} className={`rounded-lg border p-2 ${rowTone(d.state,d.closingBalance)} ${recurringBorder(d.entries)}`}><div className="flex justify-between gap-2"><time dateTime={d.dateKey} className="w-24 shrink-0 text-xs"><span className="block font-semibold">{weekday.format(date)}</span><span className="block">{ordinal(d.day)} {shortMonth.format(date)}</span>{d.state==="today"&&<span className="block uppercase">{UI_TEXT.forecast.today}</span>}</time><div className="min-w-0 flex-1">{d.entries.length?d.entries.map(x=><p key={x.id} className={x.excluded?"line-through opacity-50":""}>{x.direction==="income"?"+":"−"}{money.format(x.amount)} {x.description}</p>):<small>{UI_TEXT.forecast.noActivity}</small>}</div><b>{money.format(d.closingBalance)}</b>{d.entries.some(x=>x.source==="actual")&&<button onClick={()=>setDialog(d.dateKey)} aria-label={UI_TEXT.forecast.editDay(d.dateKey)}><FiEdit2/></button>}</div></li>})}</ol></section>
 <button onClick={()=>setDialog("add")} aria-label={UI_TEXT.forecast.add} className="fixed bottom-24 left-1/2 z-30 flex size-14 translate-x-[calc(12rem-3.5rem)] items-center justify-center rounded-full bg-emerald-600 text-white"><FiPlus/></button>
 {dialog==="opening"&&<Modal title={UI_TEXT.forecast.editOpeningBalance} close={()=>setDialog(null)}><form onSubmit={submitOpening}><Input name="amount" label={UI_TEXT.forecast.openingBalance} type="number" value={opening}/><Reason/><Actions saving={saving}/></form></Modal>}
 {dialog==="add"&&<Modal title={UI_TEXT.forecast.addOneOffTitle} close={()=>setDialog(null)}><form onSubmit={submitAdd}><label>Type<select name="kind" className="input w-full"><option value="expense">{UI_TEXT.forecast.unexpectedExpense}</option><option value="income">{UI_TEXT.forecast.oneOffIncome}</option></select></label><Input name="date" label="Date" type="date" value={`${key}-01`}/><Input name="description" label="Description"/><Input name="amount" label="Amount" type="number"/><Reason/><Actions saving={saving}/></form></Modal>}
 {dialog?.match(/^\d{4}-/)&&(()=>{const day=projection.days.find(d=>d.dateKey===dialog),entry=day?.entries.find(x=>x.source==="actual");return entry?<Modal title={UI_TEXT.forecast.editDay(dialog)} close={()=>setDialog(null)}><form onSubmit={e=>submitDay(e,dialog,entry)}><Input name="amount" label={UI_TEXT.forecast.forecastAmount} type="number" value={entry.amount}/><label className="flex justify-between">{UI_TEXT.forecast.included}<input name="included" type="checkbox" defaultChecked={!entry.excluded}/></label><Reason/><Actions saving={saving}/></form></Modal>:null})()}
 </main>}
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}){return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><section role="dialog" aria-label={title} className="w-full max-w-sm rounded-xl bg-white p-4 dark:bg-slate-900"><div className="flex justify-between"><h2 className="font-bold">{title}</h2><button onClick={close} aria-label="Close"><FiX/></button></div>{children}</section></div>}
function Input({name,label,type="text",value}:{name:string;label:string;type?:string;value?:string|number}){return <label className="mt-3 block">{label}<input required name={name} type={type} defaultValue={value} step={type==="number"?"0.01":undefined} className="input w-full px-3 py-2"/></label>};function Reason(){return <label className="mt-3 block">{UI_TEXT.forecast.changeReason}<textarea required name="reason" maxLength={160} className="input w-full"/></label>};function Actions({saving}:{saving:boolean}){return <button disabled={saving} className="mt-4 w-full rounded-lg bg-emerald-600 p-2 text-white">{saving?UI_TEXT.common.pleaseWait:UI_TEXT.common.save}</button>};function Card({label,value,action}:{label:string;value:string;action?:React.ReactNode}){return <div className="rounded-lg bg-slate-50 p-3 dark:bg-slate-800"><small>{label}</small><div className="flex gap-2 font-bold">{value}{action}</div></div>}
