export const UI_TEXT = {
  appName: "MyGrocery",
  appDescription: "Family shopping list",
  loading: "Loading...",
  common: {
    cancel: "Cancel",
    close: "Close",
    save: "Save",
    add: "Add",
    remove: "Remove",
    pleaseWait: "Please wait...",
  },
  moneyChoice: {
    title: "Which amount did you mean?",
    help: "Choose the correct amount before saving.",
  },
  navigation: {
    shopping: "Shopping",
    expenses: "Expenses",
    forecast: "Forecast",
    cashFlow: "MyCashFlow",
    admin: "Admin",
    settings: "Settings",
    menu: "Open menu",
    closeMenu: "Close menu",
  },
  forecast: {
    title: "Cash-flow Forecast",
    subtitle: "See your projected bank balance day by day",
    setupTitle: "Forecast setup comes next",
    setupDescription:
      "The next milestone will add monthly opening balances, recurring and one-off income, and recurring expenses.",
    carriedForward: "Carried forward",
    openingBalance: "Opening balance",
    editOpeningBalance: "Edit opening balance",
    openingBalanceHelp: "This is the only monthly summary value that can be edited. Carried forward and projected closing are calculated automatically.",
    difference: "Opening adjustment",
    projectedClosing: "Projected closing",
    lowestBalance: "Lowest balance",
    lowestBalanceOn: (amount: string, date: string) => `Lowest projected balance: ${amount} on ${date}`,
    avoidNegative: (amount: string, date: string) => `Need ${amount} by ${date} to avoid going below $0.`,
    maintainBuffer: (amount: string, date: string) => `Add ${amount} by ${date} to maintain the $1,500 safety buffer.`,
    notConfirmed: "Not confirmed",
    noProjection: "No projection yet",
    timelineTitle: "Daily Projection",
    timelineEmpty: "Add your opening balance and scheduled transactions to build this timeline.",
    add: "Add forecast entry",
    addOneOffTitle: "Add a one-off entry",
    oneOffIncome: "One-off income",
    unexpectedExpense: "Unexpected expense",
    entryType: "Entry type",
    entryDate: "Date",
    entryDescription: "Description",
    entryDescriptionPlaceholder: "What is this for?",
    entryAmount: "Amount",
    addEntry: "Add to forecast",
    editDay: (date: string) => `Adjust entries for ${date}`,
    editDayHelp: "Exclude an item when it should not affect your personal forecast, for example when it is paid from your wife's income.",
    expensesTotal: "Expenses section total",
    expensesTotalHelp: "This is the combined daily total from Expenses. Changing it here only adjusts the forecast and does not change the original expense records.",
    forecastAmount: "Amount used in forecast",
    saveAdjustments: "Save adjustments",
    changeReason: "Reason for change",
    changeReasonPlaceholder: "Why is this adjustment needed?",
    auditTrail: "Audit trail",
    noAuditHistory: "No changes recorded yet",
    changedFromTo: (from: string, to: string) => `Changed from ${from} to ${to}`,
    changedByOwner: (date: string) => `Owner · ${date}`,
    included: "Included",
    excluded: "Excluded",
    excludeFromForecast: (description: string) => `Include ${description} in forecast`,
    previewOnlyHelp: "This preview is kept only until the page is refreshed.",
    mockData: "Preview data",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    today: "Today",
    projected: "Projected",
    noActivity: "No activity",
    bufferGap: (amount: string) => `${amount} below your $1,500 safety buffer`,
    bufferSafe: "Above your $1,500 safety buffer",
  },
  admin: {
    open: "Open Admin settings",
    title: "Admin",
    subtitle: "Manage household settings and integrations",
    backToShopping: "Back",
    shops: "Shops",
    shoppingCategories: "Shopping categories",
    expenseCategories: "Expense categories",
    categoryHelp: "Changes are shared with every approved household device.",
    tapToEdit: "Tap a tag to rename or delete it.",
    newCategory: "New category",
    addCategory: "Add category",
    addTitle: "Add new option",
    renameCategory: (category: string) => `Rename ${category}`,
    renameTitle: "Rename category",
    invalidCategory: "Use a unique category name with valid letters or numbers.",
    categoryAdded: (category: string) => `${category} added`,
    categoryRenamed: (oldName: string, newName: string) =>
      `${oldName} renamed to ${newName}`,
    categoryDeleted: (category: string) => `${category} removed`,
    saveFailed: "Could not save the category change.",
    loadFailed: "Could not load shared categories.",
    bankSync: "Manual bank sync",
    bankSyncDescription: "Sync each UP account separately. Includes pending transactions and checks a 48-hour overlap.",
    syncNow: "Sync now",
    syncingBank: "Syncing...",
    bankSyncResult: (imported: number, fetched: number) =>
      `${imported} new transaction${imported === 1 ? "" : "s"} ready to review (${fetched} fetched).`,
    bankSyncFailed: "UP Bank sync failed. Check the connection settings and try again.",
    openBankSyncReport: "View bank sync report",
    bankSyncReportTitle: "Bank sync report",
    bankSyncReportHelp: "Permanent history of manual bank sync attempts recorded from this release onward.",
    bankSyncAuditAll: "All sync attempts",
    bankSyncAuditEmpty: "No bank sync attempts have been recorded yet.",
    bankSyncSuccess: "Successful",
    bankSyncFailure: "Failed",
    bankSyncDevice: (suffix: string) => `Device ending ${suffix}`,
    openSyncedTransactions: "Open synced transactions for review",
    lastSync: (date: string) => `Last sync: ${date}`,
    lastSyncNever: "Last sync: Never",
    forecastSchedules: "Forecast schedules",
    forecastSchedulesHelp: "Set up income and outgoing commitments used by the cash-flow forecast.",
    openForecastAudit: "View forecast audit trail",
    forecastAuditTitle: "Forecast audit trail",
    forecastAuditHelp: "A read-only history of every forecast adjustment and schedule status change.",
    auditAll: "All activity",
    auditOpeningBalance: "Opening balance changed",
    auditDailyExpense: "Daily expense total adjusted",
    auditExcluded: "Expense total excluded",
    auditScheduleInactive: "Recurring schedule made inactive",
    auditScheduleCreated: "Recurring schedule created",
    auditOneOffCreated: "One-off forecast entry created",
    auditByOwner: "Changed by Owner",
    auditEmpty: "No forecast changes recorded yet.",
    previewOnly: "Owner only",
    addRecurringIncome: "Recurring income",
    addRecurringExpense: "Recurring expense",
    recurringIncomeTitle: "Add recurring income",
    recurringExpenseTitle: "Add recurring expense",
    scheduleName: "Name",
    scheduleAmount: "Amount",
    incomePlaceholder: "e.g. Salary",
    expensePlaceholder: "e.g. Mortgage",
    frequency: "Frequency",
    weekly: "Weekly",
    fortnightly: "Fortnightly",
    monthly: "Monthly",
    quarterly: "Every 3 months",
    yearly: "Yearly",
    firstDate: "First payment date",
    previewNotSaved: "Saved securely for approved owner devices.",
    starts: (date: string) => `Starts ${date}`,
    recurringIncomeTab: "Income",
    recurringExpenseTab: "Expenses",
    scheduleLifecycleHelp: "When an amount changes, make the old schedule inactive and add a new one.",
    nextThirtyDays: (amount: string) => `Next 30 days: ${amount}`,
    nextOccurrence: (date: string) => `Next: ${date}`,
    noUpcomingOccurrence: "No upcoming occurrence",
    active: "Active",
    inactive: "Inactive",
    makeInactive: "Make inactive",
    makeActive: "Make active",
    manageSchedule: (name: string) => `View ${name} history`,
    scheduleHistoryHelp: "Review every recorded value. Historical entries cannot be edited or deleted.",
    inactiveSince: (date: string) => `Inactive since ${date}`,
    alreadyInactive: "Already inactive",
    inactiveReason: "Reason for making inactive",
    inactiveReasonPlaceholder: "For example, amount changed or payment ended",
    auditReason: (reason: string) => `Reason: ${reason}`,
  },
  expenses: {
    title: "MyExpenses",
    all: "All",
    subtitle: "Add an expense and review it by week",
    description: "Description",
    descriptionPlaceholder: "What was it for?",
    category: "Type",
    amount: "Amount",
    add: "Add expense",
    adding: "Adding...",
    empty: "No expenses added yet",
    noMatching: "No expenses match this category",
    currentWeek: "This week",
    weekOf: (date: string) => `Week of ${date}`,
    weekRange: (range: string) => `Week ${range}`,
    more: "More",
    unusual: "Unusual",
    unusualTitle: "Unusual price",
    unusualConfirm: "This price looks unusual. Do you want to add it anyway?",
    proceed: "Proceed",
    readOnly: "You can view expenses, but only approved household members can add them.",
    weekTotal: (amount: number) => `$${amount.toFixed(2)}`,
    added: "Expense added",
    addedBy: (name: string) => `Added by ${name}`,
    addFailed: "Expense could not be added",
    duplicateTitle: "Possible duplicate expense",
    duplicateConfirm: "This expense appears to have already been added today. Save it again?",
    saveAnyway: "Save anyway",
    loadFailed: "Could not refresh expenses. Check your connection and try again.",
    invalidDescription: "Enter a short description using valid characters.",
    invalidAmount: "Enter an amount greater than $0 with up to two decimal places.",
    shiftDecimal: "Shift decimal two places right",
    amend: "Amend",
    amendmentTitle: "Add amendment",
    amendmentFor: (description: string) => `Amending: ${description}`,
    amendmentDescription: "Reason for amendment",
    amendmentPlaceholder: "Why is this being corrected?",
    adjustmentAmount: "Adjustment amount",
    adjustmentHelp: "Use a negative amount to reduce the expense or a positive amount to increase it.",
    addAmendment: "Add amendment",
    amendmentAdded: "Amendment added",
    invalidAmendment: "Enter a non-zero adjustment with up to two decimal places.",
    amendmentLabel: "Amendment",
    autoAdded: "Auto added",
    thisWeekBreakdown: "This week",
    sort: "Sort expenses",
    moreCategories: "More categories",
    sortDateNewest: "Date: newest first",
    sortDateOldest: "Date: oldest first",
    sortPriceHigh: "Price: high to low",
    sortPriceLow: "Price: low to high",
    bankPendingTitle: "UP transactions to review",
    bankPendingCount: (count: number) => `${count} pending`,
    bankAccept: "Accept",
    bankReject: "Reject",
    bankReviewTitle: "Review UP transaction",
    bankReviewHelp: "Choose the expense category before accepting this transaction.",
    bankImportedAt: (date: string) => `Bank transaction: ${date}`,
    bankAccepted: "UP transaction added to expenses",
    bankRejected: "UP transaction rejected",
    bankDecisionFailed: "Could not save your decision. Please try again.",
    bankSource: "UP Bank",
    bankSourceAccount: (account: "peu" | "shamir") => account === "shamir" ? "Shamir UP" : "Peu UP",
    bankPendingStatus: "Pending",
  },
  expenseReport: {
    open: "Open expense reports",
    title: "Expense Report",
    subtitle: "Understand household spending over time",
    back: "Back to expenses",
    day: "Day",
    week: "Week",
    month: "Month",
    year: "Year",
    previous: "Previous period",
    next: "Next period",
    today: "Current period",
    total: "Total spend",
    transactions: "Transactions",
    average: "Average",
    unusual: "Unusual",
    viewUnusual: "View unusual transactions",
    unusualTransactionsTitle: "Unusual transactions",
    unusualTransactionsSummary: (count: number, amount: string) =>
      `${count} transaction${count === 1 ? "" : "s"} · ${amount} total`,
    categoryBreakdown: "Category breakdown",
    categoryChart: "Expense category pie chart",
    categoryUp: "Up from previous period",
    categoryDown: "Down from previous period",
    periodBars: "Category comparison",
    periodBarsToDate: "Compared at the same point in each period",
    periodBarsComplete: "Comparison of both complete periods",
    previousShort: "Prev",
    currentShort: "Now",
    noExpenses: "No expenses recorded for this period",
    amendment: "Amendment",
    periodComparison: "Compared with previous period",
    periodComparisonToDate: "Compared with the same point in the previous period",
    noPreviousComparison: "No previous-period spending to compare",
    spendingUp: (amount: string, percentage: number) =>
      `Spending increased by ${amount} (${percentage}%)`,
    spendingDown: (amount: string, percentage: number) =>
      `Spending decreased by ${amount} (${percentage}%)`,
    spendingUnchanged: "Spending was unchanged",
    previousSpend: (amount: string) => `Previous period: ${amount}`,
    spendingTrend: "Spending trend",
    insights: "What stands out",
    topCategory: (category: string, amount: string, percentage: number) =>
      `${category} is the largest category at ${amount} (${percentage}% of spending).`,
    biggestIncrease: (category: string, amount: string) =>
      `${category} had the biggest increase: ${amount} more than the previous period.`,
    biggestDecrease: (category: string, amount: string) =>
      `${category} improved the most: ${amount} less than the previous period.`,
    mostFrequent: (category: string, count: number) =>
      `${category} was purchased most often with ${count} transaction${count === 1 ? "" : "s"}.`,
    largestTransaction: (description: string, amount: string) =>
      `Largest transaction: ${description} at ${amount}.`,
    unusualSummary: (count: number, amount: string) =>
      `${count} unusual transaction${count === 1 ? "" : "s"} accounted for ${amount}.`,
  },
  login: {
    subtitle: "Sign in to your family shopping list",
    familyCode: "Family Code",
    username: "Username",
    password: "Password",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalid: "Invalid login",
    failed: "Login failed",
    invalidHomeCode:
      "Home code must be 3–40 letters, numbers, hyphens, or underscores.",
    invalidUsername:
      "Username can contain only letters, numbers, hyphens, or underscores.",
    invalidPassword: "Password must be 6–128 characters.",
  },
  approval: {
    title: "Device approval required",
    description:
      "Your login was successful, but this device is not approved. Please contact the owner.",
    notApproved: "This device has not been approved yet.",
    checkFailed: "Could not check approval. Please try again.",
    check: "Check approval",
    debugDeviceId: "Local debug device UID",
    copyDeviceId: "Copy UID",
    deviceIdCopied: "UID copied",
    checking: "Checking...",
    anotherLogin: "Use another login",
  },
  input: {
    placeholder: "Add grocery item",
    itemName: "Item name",
    addTo: (groupName: string) => `Add to ${groupName}`,
    priority: "Priority",
    shop: "Shop",
    category: "Category",
  },
  views: {
    flat: "Flat",
    shop: "Shop",
    category: "Category",
    all: "All",
    noShop: "No Shop",
    noCategory: "No Category",
  },
  logout: {
    label: "Logout",
    title: "Log out of MyGrocery?",
    confirm: "Are you sure you want to logout?",
    confirmAction: "Log out",
  },
  sync: {
    offline: "Offline",
    syncing: "Syncing",
    synced: "Synced",
    offlineChanges: "Offline — changes will sync when connected",
    offlineMode: "Offline mode — changes will sync when connected",
    delayed: "Connection delayed - retrying sync...",
    uploading: "Uploading changes...",
    refreshing: "Refreshing list...",
    retry: "Retry now",
    syncingList: "Syncing shopping list",
    listSynced: "Shopping list synced",
  },
  items: {
    empty: "Your grocery list is empty",
    deleteTitle: "Delete item?",
    delete: "Delete",
    completedTitle: "Completed items",
    clearCompleted: "Clear completed",
    clearing: "Clearing...",
    complete: "Complete",
    quantityPrice: "Quantity / Unit Price",
    expectedPrice: (amount: number) => `Expected $${amount.toFixed(2)}`,
    expectedTotal: (amount: number) => `Expected total: $${amount.toFixed(2)}`,
    transferToExpenses: (amount: number) =>
      `Transfer $${amount.toFixed(2)} to Expenses & Clear`,
    transferringExpense: "Transferring...",
    transferHelp: "Transfers the final total as Grocery. Clear completed does not transfer anything.",
    shoppingTransferDescription: "Completed shopping total",
    total: (amount: number) => `Total: $${amount.toFixed(2)}`,
    remaining: (count: number) => `${count} ${count === 1 ? "item" : "items"} left`,
  },
  toast: {
    maxItems: (count: number) => `Add no more than ${count} items at once`,
    maxLength: (count: number) =>
      `Each item must be ${count} characters or fewer`,
    invalidCharacters:
      "Items can use letters, numbers, spaces, and common shopping punctuation only.",
    alreadyAdded: (names: string[], plural: boolean) =>
      `${names.join(", ")} ${plural ? "are" : "is"} already added`,
    duplicatesSkipped: (names: string[]) =>
      `${names.join(", ")} skipped — already added`,
    added: (count: number) => (count === 1 ? "Item added" : "Items added"),
    addFailed: "Item could not be added",
    deleted: (name: string) => `${name} deleted`,
    deleteFailed: "Item could not be deleted",
    completed: (name: string) => `${name} completed`,
    completeFailed: "Item could not be completed",
    cleared: "Completed list cleared",
    clearFailed: "Completed list could not be cleared",
    transferredToExpenses: (amount: number) =>
      `$${amount.toFixed(2)} transferred to Expenses`,
    transferFailed: "Shopping total could not be transferred",
  },
  personalLoans: {
    menu: "Personal Loans",
    title: "Personal Loan Ledger",
    subtitle: "Track money borrowed and every repayment",
    back: "Back",
    addLoan: "Add loan",
    addRepayment: "Record repayment",
    lender: "Borrowed from",
    reason: "Loan reason",
    originalAmount: "Loan amount",
    takenDate: "Date borrowed",
    repaidDate: "Date repaid",
    repaymentAmount: "Amount repaid",
    borrowed: "Borrowed",
    repaid: "Repaid",
    outstanding: "Outstanding",
    repaymentHistory: "Repayment history",
    noRepayments: "No repayments recorded",
    empty: "No personal loans recorded yet.",
    settled: "Paid in full",
    expandLoan: (lender: string) => `Expand paid loan from ${lender}`,
    collapseLoan: (lender: string) => `Collapse paid loan from ${lender}`,
    saveLoan: "Save loan",
    saveRepayment: "Save repayment",
    invalidLoan: "Enter who the loan came from, its reason, a valid amount, and the borrowing date.",
    invalidRepayment: "Enter a repayment greater than zero, no more than the outstanding balance, and not dated in the future.",
    loadFailed: "Could not load personal loan records.",
    saveFailed: "Could not save the personal loan record.",
  },
  errors: {
    update: "The item could not be updated. Check your connection and try again.",
    delete: "The item could not be deleted. Check your connection and try again.",
    clear:
      "Completed items could not be cleared. Check your connection and try again.",
    complete:
      "The item could not be completed. Check your connection and try again.",
  },
  editor: {
    selectPriority: "-- Select Priority --",
    selectShop: "-- Select Shop --",
    selectCategory: "-- Select Category --",
    changeShop: "Change Shop",
    changeCategory: "Change Category",
    changePriority: "Change Priority",
  },
} as const;
