export const UI_TEXT = {
  appName: "MyGrocery",
  appDescription: "Family shopping list",
  loading: "Loading...",
  common: {
    cancel: "Cancel",
    close: "Close",
    save: "Save",
    add: "Add",
    remove: "Remove",
    pleaseWait: "Please wait...",
  },
  navigation: {
    shopping: "Shopping",
    expenses: "Expenses",
    admin: "Admin",
  },
  admin: {
    title: "Admin",
    subtitle: "Manage household settings and integrations",
    shoppingCategories: "Shopping categories",
    expenseCategories: "Expense categories",
    categoryHelp: "Changes are shared with every approved household device.",
    newCategory: "New category",
    addCategory: "Add category",
    renameCategory: (category: string) => `Rename ${category}`,
    renameTitle: "Rename category",
    invalidCategory: "Use a unique category name with valid letters or numbers.",
    categoryAdded: (category: string) => `${category} added`,
    categoryRenamed: (oldName: string, newName: string) =>
      `${oldName} renamed to ${newName}`,
    saveFailed: "Could not save the category change.",
    loadFailed: "Could not load shared categories.",
    bankSync: "Manual bank sync",
    bankSyncComingSoon: "UP Bank connection and transaction review will be added next.",
    lastSyncNever: "Last sync: Never",
  },
  expenses: {
    title: "Household Expenses",
    all: "All",
    subtitle: "Add an expense and review it by week",
    description: "Description",
    descriptionPlaceholder: "What was it for?",
    category: "Type",
    amount: "Amount",
    add: "Add expense",
    adding: "Adding...",
    empty: "No expenses added yet",
    noMatching: "No expenses match this category",
    currentWeek: "This week",
    weekOf: (date: string) => `Week of ${date}`,
    weekRange: (range: string) => `Week ${range}`,
    more: "More",
    unusual: "Unusual",
    unusualTitle: "Unusual price",
    unusualConfirm: "This price looks unusual. Do you want to add it anyway?",
    proceed: "Proceed",
    readOnly: "You can view expenses, but only approved household members can add them.",
    weekTotal: (amount: number) => `$${amount.toFixed(2)}`,
    added: "Expense added",
    addedBy: (name: string) => `Added by ${name}`,
    addFailed: "Expense could not be added",
    duplicateTitle: "Possible duplicate expense",
    duplicateConfirm: "This expense appears to have already been added today. Save it again?",
    saveAnyway: "Save anyway",
    loadFailed: "Could not refresh expenses. Check your connection and try again.",
    invalidDescription: "Enter a short description using valid characters.",
    invalidAmount: "Enter an amount greater than $0 with up to two decimal places.",
    shiftDecimal: "Shift decimal two places right",
    amend: "Amend",
    amendmentTitle: "Add amendment",
    amendmentFor: (description: string) => `Amending: ${description}`,
    amendmentDescription: "Reason for amendment",
    amendmentPlaceholder: "Why is this being corrected?",
    adjustmentAmount: "Adjustment amount",
    adjustmentHelp: "Use a negative amount to reduce the expense or a positive amount to increase it.",
    addAmendment: "Add amendment",
    amendmentAdded: "Amendment added",
    invalidAmendment: "Enter a non-zero adjustment with up to two decimal places.",
    amendmentLabel: "Amendment",
    autoAdded: "Auto added",
    thisWeekBreakdown: "This week",
    sort: "Sort expenses",
    moreCategories: "More categories",
    sortDateNewest: "Date: newest first",
    sortDateOldest: "Date: oldest first",
    sortPriceHigh: "Price: high to low",
    sortPriceLow: "Price: low to high",
  },
  expenseReport: {
    open: "Open expense reports",
    title: "Expense Report",
    subtitle: "Understand household spending over time",
    back: "Back to expenses",
    day: "Day",
    week: "Week",
    month: "Month",
    year: "Year",
    previous: "Previous period",
    next: "Next period",
    today: "Current period",
    total: "Total spend",
    transactions: "Transactions",
    average: "Average",
    unusual: "Unusual",
    viewUnusual: "View unusual transactions",
    unusualTransactionsTitle: "Unusual transactions",
    unusualTransactionsSummary: (count: number, amount: string) =>
      `${count} transaction${count === 1 ? "" : "s"} · ${amount} total`,
    categoryBreakdown: "Category breakdown",
    categoryChart: "Expense category pie chart",
    categoryUp: "Up from previous period",
    categoryDown: "Down from previous period",
    periodBars: "Category comparison",
    periodBarsToDate: "Compared at the same point in each period",
    periodBarsComplete: "Comparison of both complete periods",
    previousShort: "Prev",
    currentShort: "Now",
    noExpenses: "No expenses recorded for this period",
    amendment: "Amendment",
    periodComparison: "Compared with previous period",
    periodComparisonToDate: "Compared with the same point in the previous period",
    noPreviousComparison: "No previous-period spending to compare",
    spendingUp: (amount: string, percentage: number) =>
      `Spending increased by ${amount} (${percentage}%)`,
    spendingDown: (amount: string, percentage: number) =>
      `Spending decreased by ${amount} (${percentage}%)`,
    spendingUnchanged: "Spending was unchanged",
    previousSpend: (amount: string) => `Previous period: ${amount}`,
    spendingTrend: "Spending trend",
    insights: "What stands out",
    topCategory: (category: string, amount: string, percentage: number) =>
      `${category} is the largest category at ${amount} (${percentage}% of spending).`,
    biggestIncrease: (category: string, amount: string) =>
      `${category} had the biggest increase: ${amount} more than the previous period.`,
    biggestDecrease: (category: string, amount: string) =>
      `${category} improved the most: ${amount} less than the previous period.`,
    mostFrequent: (category: string, count: number) =>
      `${category} was purchased most often with ${count} transaction${count === 1 ? "" : "s"}.`,
    largestTransaction: (description: string, amount: string) =>
      `Largest transaction: ${description} at ${amount}.`,
    unusualSummary: (count: number, amount: string) =>
      `${count} unusual transaction${count === 1 ? "" : "s"} accounted for ${amount}.`,
  },
  login: {
    subtitle: "Sign in to your family shopping list",
    familyCode: "Family Code",
    username: "Username",
    password: "Password",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalid: "Invalid login",
    failed: "Login failed",
    invalidHomeCode:
      "Home code must be 3–40 letters, numbers, hyphens, or underscores.",
    invalidUsername:
      "Username can contain only letters, numbers, hyphens, or underscores.",
    invalidPassword: "Password must be 6–128 characters.",
  },
  approval: {
    title: "Device approval required",
    description:
      "Your login was successful, but this device is not approved. Please contact the owner.",
    notApproved: "This device has not been approved yet.",
    checkFailed: "Could not check approval. Please try again.",
    check: "Check approval",
    checking: "Checking...",
    anotherLogin: "Use another login",
  },
  input: {
    placeholder: "Add grocery item",
    itemName: "Item name",
    addTo: (groupName: string) => `Add to ${groupName}`,
    priority: "Priority",
    shop: "Shop",
    category: "Category",
  },
  views: {
    flat: "Flat",
    shop: "Shop",
    category: "Category",
    all: "All",
    noShop: "No Shop",
    noCategory: "No Category",
  },
  logout: {
    label: "Logout",
    confirm: "Are you sure you want to logout?",
  },
  sync: {
    offline: "Offline",
    syncing: "Syncing",
    synced: "Synced",
    offlineChanges: "Offline — changes will sync when connected",
    offlineMode: "Offline mode — changes will sync when connected",
    delayed: "Connection delayed - retrying sync...",
    uploading: "Uploading changes...",
    refreshing: "Refreshing list...",
    retry: "Retry now",
    syncingList: "Syncing shopping list",
    listSynced: "Shopping list synced",
  },
  items: {
    empty: "Your grocery list is empty",
    deleteTitle: "Delete item?",
    delete: "Delete",
    completedTitle: "Completed items",
    clearCompleted: "Clear completed",
    clearing: "Clearing...",
    complete: "Complete",
    quantityPrice: "Quantity / Unit Price",
    expectedPrice: (amount: number) => `Expected $${amount.toFixed(2)}`,
    expectedTotal: (amount: number) => `Expected total: $${amount.toFixed(2)}`,
    transferToExpenses: (amount: number) =>
      `Transfer $${amount.toFixed(2)} to Expenses & Clear`,
    transferringExpense: "Transferring...",
    transferHelp: "Transfers the final total as Grocery. Clear completed does not transfer anything.",
    shoppingTransferDescription: "Completed shopping total",
    total: (amount: number) => `Total: $${amount.toFixed(2)}`,
    remaining: (count: number) => `${count} ${count === 1 ? "item" : "items"} left`,
  },
  toast: {
    maxItems: (count: number) => `Add no more than ${count} items at once`,
    maxLength: (count: number) =>
      `Each item must be ${count} characters or fewer`,
    invalidCharacters:
      "Items can use letters, numbers, spaces, and common shopping punctuation only.",
    alreadyAdded: (names: string[], plural: boolean) =>
      `${names.join(", ")} ${plural ? "are" : "is"} already added`,
    duplicatesSkipped: (names: string[]) =>
      `${names.join(", ")} skipped — already added`,
    added: (count: number) => (count === 1 ? "Item added" : "Items added"),
    addFailed: "Item could not be added",
    deleted: (name: string) => `${name} deleted`,
    deleteFailed: "Item could not be deleted",
    completed: (name: string) => `${name} completed`,
    completeFailed: "Item could not be completed",
    cleared: "Completed list cleared",
    clearFailed: "Completed list could not be cleared",
    transferredToExpenses: (amount: number) =>
      `$${amount.toFixed(2)} transferred to Expenses`,
    transferFailed: "Shopping total could not be transferred",
  },
  errors: {
    update: "The item could not be updated. Check your connection and try again.",
    delete: "The item could not be deleted. Check your connection and try again.",
    clear:
      "Completed items could not be cleared. Check your connection and try again.",
    complete:
      "The item could not be completed. Check your connection and try again.",
  },
  editor: {
    selectPriority: "-- Select Priority --",
    selectShop: "-- Select Shop --",
    selectCategory: "-- Select Category --",
    changeShop: "Change Shop",
    changeCategory: "Change Category",
    changePriority: "Change Priority",
  },
} as const;
