export const UI_TEXT = {
  appName: "MyGrocery",
  appDescription: "Family shopping list",
  loading: "Loading...",
  common: {
    cancel: "Cancel",
    close: "Close",
    save: "Save",
    add: "Add",
    remove: "Remove",
    pleaseWait: "Please wait...",
  },
  navigation: {
    shopping: "Shopping",
    expenses: "Expenses",
  },
  expenses: {
    title: "Household Expenses",
    all: "All",
    subtitle: "Add an expense and review it by week",
    description: "Description",
    descriptionPlaceholder: "What was it for?",
    category: "Type",
    amount: "Amount",
    add: "Add expense",
    adding: "Adding...",
    empty: "No expenses added yet",
    noMatching: "No expenses match this category",
    currentWeek: "This week",
    weekOf: (date: string) => `Week of ${date}`,
    weekRange: (range: string) => `Week ${range}`,
    more: "More",
    unusual: "Unusual",
    unusualTitle: "Unusual price",
    unusualConfirm: "This price looks unusual. Do you want to add it anyway?",
    proceed: "Proceed",
    readOnly: "You can view expenses, but only approved household members can add them.",
    weekTotal: (amount: number) => `$${amount.toFixed(2)}`,
    added: "Expense added",
    addFailed: "Expense could not be added",
    loadFailed: "Could not refresh expenses. Check your connection and try again.",
    invalidDescription: "Enter a short description using valid characters.",
    invalidAmount: "Enter an amount greater than $0 with up to two decimal places.",
    amend: "Amend",
    amendmentTitle: "Add amendment",
    amendmentFor: (description: string) => `Amending: ${description}`,
    amendmentDescription: "Reason for amendment",
    amendmentPlaceholder: "Why is this being corrected?",
    adjustmentAmount: "Adjustment amount",
    adjustmentHelp: "Use a negative amount to reduce the expense or a positive amount to increase it.",
    addAmendment: "Add amendment",
    amendmentAdded: "Amendment added",
    invalidAmendment: "Enter a non-zero adjustment with up to two decimal places.",
    amendmentLabel: "Amendment",
    thisWeekBreakdown: "This week",
    sort: "Sort expenses",
    moreCategories: "More categories",
    sortDateNewest: "Date: newest first",
    sortDateOldest: "Date: oldest first",
    sortPriceHigh: "Price: high to low",
    sortPriceLow: "Price: low to high",
  },
  login: {
    subtitle: "Sign in to your family shopping list",
    familyCode: "Family Code",
    username: "Username",
    password: "Password",
    signIn: "Sign In",
    signingIn: "Signing in...",
    invalid: "Invalid login",
    failed: "Login failed",
    invalidHomeCode:
      "Home code must be 3–40 letters, numbers, hyphens, or underscores.",
    invalidUsername:
      "Username can contain only letters, numbers, hyphens, or underscores.",
    invalidPassword: "Password must be 6–128 characters.",
  },
  approval: {
    title: "Device approval required",
    description:
      "Your login was successful, but this device is not approved. Please contact the owner.",
    notApproved: "This device has not been approved yet.",
    checkFailed: "Could not check approval. Please try again.",
    check: "Check approval",
    checking: "Checking...",
    anotherLogin: "Use another login",
  },
  input: {
    placeholder: "Add grocery item",
    itemName: "Item name",
    addTo: (groupName: string) => `Add to ${groupName}`,
    priority: "Priority",
    shop: "Shop",
    category: "Category",
  },
  views: {
    flat: "Flat",
    shop: "Shop",
    category: "Category",
    all: "All",
    noShop: "No Shop",
    noCategory: "No Category",
  },
  logout: {
    label: "Logout",
    confirm: "Are you sure you want to logout?",
  },
  sync: {
    offline: "Offline",
    syncing: "Syncing",
    synced: "Synced",
    offlineChanges: "Offline — changes will sync when connected",
    offlineMode: "Offline mode — changes will sync when connected",
    delayed: "Connection delayed - retrying sync...",
    uploading: "Uploading changes...",
    refreshing: "Refreshing list...",
    retry: "Retry now",
    syncingList: "Syncing shopping list",
    listSynced: "Shopping list synced",
  },
  items: {
    empty: "Your grocery list is empty",
    deleteTitle: "Delete item?",
    delete: "Delete",
    completedTitle: "Completed items",
    clearCompleted: "Clear completed",
    clearing: "Clearing...",
    complete: "Complete",
    quantityPrice: "Quantity / Unit Price",
    total: (amount: number) => `Total: $${amount.toFixed(2)}`,
    remaining: (count: number) => `${count} ${count === 1 ? "item" : "items"} left`,
  },
  toast: {
    maxItems: (count: number) => `Add no more than ${count} items at once`,
    maxLength: (count: number) =>
      `Each item must be ${count} characters or fewer`,
    invalidCharacters:
      "Items can use letters, numbers, spaces, and common shopping punctuation only.",
    alreadyAdded: (names: string[], plural: boolean) =>
      `${names.join(", ")} ${plural ? "are" : "is"} already added`,
    duplicatesSkipped: (names: string[]) =>
      `${names.join(", ")} skipped — already added`,
    added: (count: number) => (count === 1 ? "Item added" : "Items added"),
    addFailed: "Item could not be added",
    deleted: (name: string) => `${name} deleted`,
    deleteFailed: "Item could not be deleted",
    completed: (name: string) => `${name} completed`,
    completeFailed: "Item could not be completed",
    cleared: "Completed list cleared",
    clearFailed: "Completed list could not be cleared",
  },
  errors: {
    update: "The item could not be updated. Check your connection and try again.",
    delete: "The item could not be deleted. Check your connection and try again.",
    clear:
      "Completed items could not be cleared. Check your connection and try again.",
    complete:
      "The item could not be completed. Check your connection and try again.",
  },
  editor: {
    selectPriority: "-- Select Priority --",
    selectShop: "-- Select Shop --",
    selectCategory: "-- Select Category --",
    changeShop: "Change Shop",
    changeCategory: "Change Category",
    changePriority: "Change Priority",
  },
} as const;
